### ISSUE TITLE
Ergänzungs- und Änderungswünsche für mein.silberpfoten.de - Besprechung am 17.1.2024

### ISSUE THREAD

**Issue by SanQu** [TSV-Stuttgart/SilberPfoten#16]
- [x] 1.	Probleme beim Einloggen mancher User gelöst? _Nachdem keine weiteren Meldungen kamen, wurden wir nicht aktiv._
- [x] 2.	Probleme beim Registrieren mancher User gelöst? _Nachdem keine weiteren Meldungen kamen, wurden wir nicht aktiv._
- [x] 3.	Es wurden offenbar nicht alle bestehenden Anmeldungen importiert  _Hier schaut Kara nochmal in die Excel ob der User sich bewusst gelöscht hat oder tatsächlich ein Import Problem stattgefunden hat_
- [x] 4.	Automatische Kontrolle Geburtsdatum beim Registrieren einführen, damit sich nur volljährige Personen anmelden können #17 
- [x] 5.	Doppelte Registrierung sollte ausgeschlossen sein (es haben sich einige neu registriert, die bereits im Verteiler waren) _Zwecks E-Mail Adresse Unique, darf das nicht sein. Bei Kontrolle konnten wir keine doppelten ermitteln_  #18
- [x] 6.	Gibt es einen Adressabgleich mit Google? #19
- [x] 7.	User-Löschung und Fallübernahme nicht mehr an k.*******@gmx.net senden, sondern nur an ****@gmail.com #24

- [x] 8.	Manchmal erhalten wir E-Mail mit Fallübernahme, aber die Person taucht dann nicht in der Bewerberliste auf => woran kann das liegen? (z.B. ... u.a.) _Wenn die Person sich wieder storniert, verschwindet sie_
- [x] 9.	Bei Ehrenamtlichen, die bereits vor Einführung des neuen Systems angemeldet waren, sehen wir keine Telefonnummer #20
- [x] 10.	Wenn man Bewerber für Fallübernahme ablehnt: Erhält der Bewerber eine Infomail darüber? Kann man eine Ablehnung mit einer Nachricht „Bedarf bereits gedeckt“ verknüpfen? _Hier erhalten wir von Karo ein Template_ #21
- [x] 11.	Wenn wir eine Neuregistrierung ablehnen und sperren oder löschen, erhält die Person darüber eine Nachricht? _Nein_
- [x] 12.	Wenn man bei neuen Suchaufträgen „Hundeerfahrung“ anklickt, bekommen den Suchauftrag aber trotzdem alle User in dem Suchradius, nicht nur die, die Hundeerfahrung angegeben haben, oder? _Nein. Es werden momentan allen Usern alle Suchaufträge angezeigt._
- [x] 13.	Menüpunkt „Nachrichten“: Wie/wozu kann er genutzt werden? _Klärung wo es angezeigt wird_ #23
- [x] 14.	Über das Handy hatte ich trotz normalem Einloggen keine Administratorrechte #22 
- [x] 15.	Wir brauchen die Möglichkeit, eine Excel-Datei der Ehrenamtlichen zu exportieren #25 #26 #27
- [x] 16.	Es sollte irgendwo angezeigt werden, wie viele Mitglieder wir haben #28
- [x] 17.	Kann man irgendwo sehen, wer sich wann registriert hat oder wie viele an einem bestimmten Tag? #29
- [x] 18.	In Gesamtliste der Benutzer direkt auch Telefonnummer und ihre angebotenen Hilfstätigkeiten anzeigen #30
- [x] 19.	Weitere Option für Suchaufträge einrichten: bisher kann man sie nur bearbeiten oder löschen; gut wäre eine Art Archiv/ein Schließen des Falls, so dass man die Aufträge reaktivieren und auch weiterhin sehen kann, wer sich als Helfer gemeldet hat. Mitglieder sollten das Archiv einsehen, aber sich nicht mehr für den Fall bewerben können #31
- [x] 20.	Bei Suchaufträgen wird meist eine Tel.nr., manchmal aber stattdessen eine E-Mail-Adresse angegeben, den freigegebenen Bewerbern wird nur die Telefonnr. angezeigt => kann ihnen das Feld angezeigt werden, wo etwas drinsteht (also entweder Tel.nr. oder E-Mail oder beides)? #32
- [x] 21.	Bei Aktivierung neuer Nutzer: Nach Ansehen der Daten der neuen Person und nach der Aktivierung springt es immer wieder auf die Liste der aktiven Mitglieder, d.h. man muss sehr viel hin und her klicken #33
- [x] 22.	Suchradius: Auch unter 1 km möglich (0,5 km o.ä.)? Im Stuttgarter Stadtgebiet gibt es manchmal selbst bei 1 km Suchradius sehr viele Empfänger (ggf. zu viele) #34
- [x] 23.	Beim Menü des Users soll es noch einen Menüpunkt „Spenden/Patenschaft“ geben, von dem zur entsprechenden Seite auf unserer Webseite verlinkt wird #35
- [x] 24.	„Nachricht senden“-Möglichkeit an einzelne Benutzer in der Gesamtliste (Ergänzung bei den 3 Punkten hinter jedem Benutzer) #36
- [x] 25.	Bei Nachrichten Filter nach PLZ, Profession etc. einfügen #37
- [x] 26.	Suchaufträge: es sollte erkennbar sein, wie viele Leute sich als Helfer beworben haben und wie viele bereits akzeptiert wurden #38

**Comment by SanQu** [comment]
Alle Features wurden implementiert und umgesetzt. Daher schließe ich das Ticket.
